[build-system]
requires = ["setuptools>64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dsnleds"
version = "0.1"
requires-python = ">=3.7"
dependencies = [
    "requests>=2.21",
    "lxml>4.3.2"
]

[project.scripts]
dsn-leds = "dsnleds:main"
